---

services: "docker"

env:
  - distro: "ubuntu1804"
  - distro: "ubuntu2004"
  - distro: "debian9"
  - distro: "debian10"

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/nickjj/d12353b5b601e33cd62fda111359957a/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
